/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controlador.MiembroData;
import Modelo.Miembro;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ViewBuscarMiembro extends javax.swing.JFrame {

    private MiembroData miemData;

    /**
     * Creates new form ViewBuscarMiembro
     */
    public ViewBuscarMiembro() {
    }

    ViewBuscarMiembro(MiembroData miemData) {
        initComponents();
        this.miemData = miemData;
        radBtnEstado.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblApellido = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblProyecto = new javax.swing.JLabel();
        lblLegajoMiembro = new javax.swing.JLabel();
        txtIdMiembro = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblTituloBuscaMiembro = new javax.swing.JLabel();
        lblEstadoEquipo = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        radBtnEstado = new javax.swing.JRadioButton();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblEliminar = new javax.swing.JLabel();
        radBtnEliminar = new javax.swing.JRadioButton();
        lblActivoONo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblApellido.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblApellido.setText("Apellido:");

        lblProyecto.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblProyecto.setText("Documento:");

        lblLegajoMiembro.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblLegajoMiembro.setText("Legajo Miembro:");

        btnBuscar.setBackground(new java.awt.Color(25, 255, 10));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblTituloBuscaMiembro.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        lblTituloBuscaMiembro.setText("Buscar Miembro");

        lblEstadoEquipo.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblEstadoEquipo.setText("Estado:");

        btnGuardar.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        radBtnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnEstadoActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        lblEliminar.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblEliminar.setText("Eliminar:");

        radBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnEliminarActionPerformed(evt);
            }
        });

        lblActivoONo.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblActivoONo.setText("                ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellido)
                    .addComponent(lblLegajoMiembro)
                    .addComponent(lblEstadoEquipo)
                    .addComponent(lblNombre)
                    .addComponent(lblProyecto)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(radBtnEstado)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblActivoONo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                    .addComponent(lblEliminar)
                                    .addGap(6, 6, 6)
                                    .addComponent(radBtnEliminar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBuscar)))
                            .addComponent(txtIdMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTituloBuscaMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTituloBuscaMiembro)
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProyecto)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellido)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLegajoMiembro)
                            .addComponent(txtIdMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstadoEquipo)
                            .addComponent(radBtnEstado)
                            .addComponent(radBtnEliminar)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEliminar)
                            .addComponent(lblActivoONo))
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radBtnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnEstadoActionPerformed
        // TODO add your handling code here:
        estadoBtn();


    }//GEN-LAST:event_radBtnEstadoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        radBtnEliminar.setSelected(false);
        radBtnEstado.setEnabled(false);
        Integer dni = 0;

        try {
            dni = Integer.parseInt(txtDNI.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Valor ingresado invalido, ingrese numeros para el DNI");
            txtDNI.requestFocus(); // vuelve al componente DNI
            return; // Salimos del método
        }

        //Miembro miem = new Miembro();
        Miembro miem = miemData.buscarMiembroPorDni(dni);

        if (miem != null) { // Ahora comprobamos si el miembro es null, en lugar de verificar si el ID es 0

            String idMiembro = String.valueOf(miem.getIdMiembro());
            String dniMiembro = String.valueOf(miem.getDni());

            txtIdMiembro.setText(idMiembro);
            txtApellido.setText(miem.getApellido());
            txtNombre.setText(miem.getNombre());
            txtDNI.setText(dniMiembro);
            radBtnEstado.setSelected(miem.isEstado());

            estadoBtn();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró un miembro con ese DNI");
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        ViewPpalMiembro ppalMiembro = new ViewPpalMiembro(miemData);
        ppalMiembro.setVisible(true);
        ppalMiembro.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de guardar los cambios?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {

            Integer id = Integer.parseInt(txtIdMiembro.getText());
            int dni = Integer.parseInt(txtDNI.getText());
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            Boolean estado = radBtnEstado.isSelected();

            Miembro miem = new Miembro(dni, apellido, nombre, estado);

            miemData.modificarMiembro(id, miem);

        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void radBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnEliminarActionPerformed
        // TODO add your handling code here:

        radBtnEliminar.setSelected(true);
        int opcion = JOptionPane.showConfirmDialog(this, "¿Desea Eliminar este miembro?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            radBtnEstado.setEnabled(true);
            radBtnEstado.setSelected(false);
        } else {
            radBtnEstado.setEnabled(false);
            radBtnEstado.setSelected(true);
            radBtnEliminar.setSelected(false);
        }
        estadoBtn();

    }//GEN-LAST:event_radBtnEliminarActionPerformed
    public void limpiar() {
        txtApellido.setText("");
        txtNombre.setText("");
        txtIdMiembro.setText("");
        txtDNI.setText("");
        radBtnEstado.setEnabled(false);
        radBtnEstado.setSelected(false);
        radBtnEliminar.setSelected(false);
    }

    public void estadoBtn() {
        if (radBtnEstado.isSelected()) {

            lblActivoONo.setText("Activo");
            lblActivoONo.setForeground(Color.BLACK);
        } else {
            lblActivoONo.setText("Eliminar ");
            lblActivoONo.setForeground(Color.RED);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblActivoONo;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblEstadoEquipo;
    private javax.swing.JLabel lblLegajoMiembro;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProyecto;
    private javax.swing.JLabel lblTituloBuscaMiembro;
    private javax.swing.JRadioButton radBtnEliminar;
    private javax.swing.JRadioButton radBtnEstado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtIdMiembro;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
