/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controlador.EquipoData;
import Controlador.ProyectoData;
import Modelo.Equipo;
import Modelo.Proyecto;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicolas
 */
public class ViewBuscarProyec extends javax.swing.JFrame {

    private ProyectoData pd;
    private EquipoData equiData;

    /**
     * Creates new form ViewBuscarProyec
     */
    public ViewBuscarProyec() {
        initComponents();
    }

    ViewBuscarProyec(ProyectoData proyectoData, EquipoData equiData) {
        initComponents();
        this.pd = proyectoData;
        this.equiData = equiData;
        txtIdProyecto.setEnabled(false);
        radBtnEstadoProyecto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        lblTituloBuscarProyec = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblNombreProyecto = new javax.swing.JLabel();
        txtNombreProyecto = new javax.swing.JTextField();
        lblFechaInicio = new javax.swing.JLabel();
        dateFechaInicio = new com.toedter.calendar.JDateChooser();
        lblEquipo = new javax.swing.JLabel();
        lblIdProyecto = new javax.swing.JLabel();
        txtIdProyecto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        radBtnEstadoProyecto = new javax.swing.JRadioButton();
        lblEstado = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtEquipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblTituloBuscarProyec.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        lblTituloBuscarProyec.setText("Buscar Proyecto");

        btnSalir.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnGuardar.setText("Modificar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblNombreProyecto.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblNombreProyecto.setText("Nombre Proyecto:");

        lblFechaInicio.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblFechaInicio.setText("Fecha de Inicio:");

        lblEquipo.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblEquipo.setText("Equipo Asignado:");

        lblIdProyecto.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblIdProyecto.setText("Número de Proyecto:");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 0, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        radBtnEstadoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnEstadoProyectoActionPerformed(evt);
            }
        });

        lblEstado.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblEstado.setText("Estado:");

        lblDescripcion.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblDescripcion.setText("Descripción:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaInicio)
                    .addComponent(lblEquipo)
                    .addComponent(lblEstado)
                    .addComponent(lblDescripcion)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNombreProyecto)
                    .addComponent(lblIdProyecto))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(txtEquipo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreProyecto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdProyecto))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(radBtnEstadoProyecto)
                    .addComponent(dateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloBuscarProyec, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTituloBuscarProyec)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNombreProyecto)
                                    .addComponent(txtNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIdProyecto)
                                    .addComponent(txtIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaInicio))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEquipo)
                            .addComponent(txtEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(radBtnEstadoProyecto))
                    .addComponent(lblEstado))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        ViewPpalProyec ppalProyec = new ViewPpalProyec(pd, equiData);
        ppalProyec.setVisible(true);
        ppalProyec.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String nombreProyecto = txtNombreProyecto.getText();

        boolean band = false;

        if (nombreProyecto == null || nombreProyecto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el nombre del proyecto.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         ArrayList<Equipo> listaEqu = (ArrayList<Equipo>) equiData.listarEquipo();
        Proyecto proyecto = pd.buscarProyectoPorNombre(nombreProyecto);
        
         if (proyecto == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el proyecto.", "Error", JOptionPane.ERROR_MESSAGE);
            limpiar();
            return;
        }System.out.println(proyecto);
        
        if (proyecto.getIdProyecto() != 0) {
            txtIdProyecto.setText(String.valueOf(proyecto.getIdProyecto()));
            txtDescripcion.setText(proyecto.getDescripcion());
            dateFechaInicio.setDate(java.sql.Date.valueOf(proyecto.getFechaInicio()));
            
            for (Equipo equipo : listaEqu) {
                int idPro = Integer.parseInt(txtIdProyecto.getText());
                int id = equipo.getProyecto().getIdProyecto();
                if (id == idPro) {
                    String idProyect = String.valueOf(id);
                    txtEquipo.setText("N° " + idProyect + ", " + equipo.getNombre());
                    band = true;
                }
            }
            if (!band) {
                txtEquipo.setText("Sin equipo asignado");
            }
            txtEquipo.setEnabled(false);
            radBtnEstadoProyecto.setSelected(proyecto.isEstado());
        } else {
            limpiar();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void radBtnEstadoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnEstadoProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnEstadoProyectoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de guardar?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            //si confirma que si, empezar con el codigo aca abajo
            int idPro = Integer.parseInt(txtIdProyecto.getText());
            Proyecto pro = new Proyecto();

            pro.setNombre(txtNombreProyecto.getText());
            pro.setDescripcion(txtDescripcion.getText());
            pro.setEstado(true);

            Date sfecha = dateFechaInicio.getDate();
            LocalDate fechaIn = sfecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            pro.setFechaInicio(fechaIn);

            pd.modificarProyecto(idPro, pro);
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    public void limpiar() {
        txtNombreProyecto.setText("");
        txtIdProyecto.setText("");
        txtEquipo.setText("");
        txtDescripcion.setText("");
        radBtnEstadoProyecto.setSelected(false);
        dateFechaInicio.setDate(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private com.toedter.calendar.JDateChooser dateFechaInicio;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblIdProyecto;
    private javax.swing.JLabel lblNombreProyecto;
    private javax.swing.JLabel lblTituloBuscarProyec;
    private javax.swing.JRadioButton radBtnEstadoProyecto;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEquipo;
    private javax.swing.JTextField txtIdProyecto;
    private javax.swing.JTextField txtNombreProyecto;
    // End of variables declaration//GEN-END:variables
}
