/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controlador.ComentariosData;
import Controlador.EquipoData;
import Controlador.EquipoMiembrosData;
import Controlador.MiembroData;
import Controlador.ProyectoData;
import Controlador.TareaData;
import Modelo.Comentarios;
import Modelo.Miembro;
import Modelo.Tarea;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolas
 */
public class ViewFiltroTareas extends javax.swing.JFrame {

    private ProyectoData proyecData;
    private EquipoData equiData;
    private EquipoMiembrosData equiMiemData;
    private MiembroData miemData;
    private TareaData tareaData;
    private ComentariosData comData;
    private Miembro miemSel;
    private Tarea tareaSel;
    private DefaultTableModel modelo;
    private int idEquipo;

    /**
     * Creates new form ViewFiltroTareas
     */
    public ViewFiltroTareas() {
        initComponents();
        radBtnPendiente.setSelected(true);
        modelo = new DefaultTableModel();
        armarCabeceraTabla();
        limpiarTabla();
        llenarTabla();

    }

    public ViewFiltroTareas(ProyectoData proyecData, EquipoData equiData, EquipoMiembrosData equiMiemData, MiembroData miemData, TareaData tareaData, ComentariosData comData, Miembro miemSel, Tarea tareaSel, int idEquipo) {
        initComponents();
        this.proyecData = proyecData;
        this.equiData = equiData;
        this.equiMiemData = equiMiemData;
        this.miemData = miemData;
        this.tareaData = tareaData;
        this.comData = comData;
        this.miemSel = miemSel;
        this.tareaSel = tareaSel;
        this.idEquipo = idEquipo;
        radBtnPendiente.setSelected(true);
        modelo = new DefaultTableModel();
        armarCabeceraTabla();
        limpiarTabla();
        llenarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        lblTituloBuscaMiembro = new javax.swing.JLabel();
        Terminadas = new javax.swing.JLabel();
        radBtnTerminadas = new javax.swing.JRadioButton();
        radBtnProceso = new javax.swing.JRadioButton();
        Terminadas1 = new javax.swing.JLabel();
        radBtnPendiente = new javax.swing.JRadioButton();
        Terminadas2 = new javax.swing.JLabel();
        radBtnDesactivadas = new javax.swing.JRadioButton();
        Terminadas3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTareas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalir.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblTituloBuscaMiembro.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        lblTituloBuscaMiembro.setText("Obtener Tareas");

        Terminadas.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Terminadas.setText("Terminadas:");

        radBtnTerminadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnTerminadasActionPerformed(evt);
            }
        });

        radBtnProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnProcesoActionPerformed(evt);
            }
        });

        Terminadas1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Terminadas1.setText("En Proceso:");

        radBtnPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnPendienteActionPerformed(evt);
            }
        });

        Terminadas2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Terminadas2.setText("Pendientes:");

        radBtnDesactivadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnDesactivadasActionPerformed(evt);
            }
        });

        Terminadas3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Terminadas3.setText("Desactivadas");

        tablaTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tablaTareas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTituloBuscaMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(Terminadas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radBtnTerminadas)
                                    .addGap(18, 18, 18)
                                    .addComponent(Terminadas1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radBtnProceso)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Terminadas2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radBtnPendiente)
                                    .addGap(18, 18, 18)
                                    .addComponent(Terminadas3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(radBtnDesactivadas))
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTituloBuscaMiembro)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radBtnDesactivadas)
                            .addComponent(Terminadas3)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radBtnProceso)
                        .addComponent(Terminadas1)
                        .addComponent(Terminadas2)
                        .addComponent(radBtnPendiente))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Terminadas)
                        .addComponent(radBtnTerminadas)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radBtnTerminadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnTerminadasActionPerformed
        // TODO add your handling code here:

        radBtnTerminadas.setSelected(true);
        radBtnProceso.setSelected(false);
        radBtnPendiente.setSelected(false);
        radBtnDesactivadas.setSelected(false);
        limpiarTabla();
        llenarTabla();

    }//GEN-LAST:event_radBtnTerminadasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        ViewVerTarea ppalBusEquipo = new ViewVerTarea(proyecData, equiData, equiMiemData, miemData, tareaData, comData, idEquipo);
        ppalBusEquipo.setVisible(true);
        ppalBusEquipo.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void radBtnProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnProcesoActionPerformed
        // TODO add your handling code here:

        radBtnProceso.setSelected(true);
        radBtnPendiente.setSelected(false);
        radBtnDesactivadas.setSelected(false);
        radBtnTerminadas.setSelected(false);
        limpiarTabla();
        llenarTabla();
    }//GEN-LAST:event_radBtnProcesoActionPerformed

    private void radBtnPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnPendienteActionPerformed
        // TODO add your handling code here:

        radBtnPendiente.setSelected(true);
        radBtnDesactivadas.setSelected(false);
        radBtnTerminadas.setSelected(false);
        radBtnProceso.setSelected(false);
        limpiarTabla();
        llenarTabla();
    }//GEN-LAST:event_radBtnPendienteActionPerformed

    private void radBtnDesactivadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnDesactivadasActionPerformed
        // TODO add your handling code here:

        radBtnDesactivadas.setSelected(true);
        radBtnTerminadas.setSelected(false);
        radBtnProceso.setSelected(false);
        radBtnPendiente.setSelected(false);
        limpiarTabla();
        llenarTabla();
    }//GEN-LAST:event_radBtnDesactivadasActionPerformed

    private void llenarTabla() {
        limpiarTabla();
        List<Tarea> tareas = new ArrayList<Tarea>();
        int idEqMiemb = equiMiemData.buscarIdMiembroEq(idEquipo, miemSel.getIdMiembro());

        tareas = tareaData.listarTareasPorIdMiembroEQ(idEqMiemb);

        int cont = 0;

        for (Tarea com : tareas) {
            cont++;

            if (radBtnTerminadas.isSelected() && com.getEstado() == 3) {
                modelo.addRow(new Object[]{cont, com.getIdTarea(), com.getNombre(), com.getEstado()});
            } else if (radBtnProceso.isSelected() && com.getEstado() == 2) {
                modelo.addRow(new Object[]{cont, com.getIdTarea(), com.getNombre(), com.getEstado()});
            } else if (radBtnPendiente.isSelected() && com.getEstado() == 1) {
                modelo.addRow(new Object[]{cont, com.getIdTarea(), com.getNombre(), com.getEstado()});
            } else if (radBtnDesactivadas.isSelected() && com.getEstado() == 0) {
                modelo.addRow(new Object[]{cont, com.getIdTarea(), com.getNombre(), com.getEstado()});
            }
        }
    }

    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("N°");
        filaCabecera.add("Orden");
        filaCabecera.add("Tarea");
        filaCabecera.add("Estado");

        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        tablaTareas.setModel(modelo);

        tablaTareas.getColumnModel().getColumn(0).setPreferredWidth(5);
        tablaTareas.getColumnModel().getColumn(1).setPreferredWidth(10);
        tablaTareas.getColumnModel().getColumn(2).setPreferredWidth(300);

    }

    private void limpiarTabla() {
        int filasModelo = modelo.getRowCount();
        for (int i = 0; i < filasModelo; i++) {
            modelo.removeRow(0);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Terminadas;
    private javax.swing.JLabel Terminadas1;
    private javax.swing.JLabel Terminadas2;
    private javax.swing.JLabel Terminadas3;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloBuscaMiembro;
    private javax.swing.JRadioButton radBtnDesactivadas;
    private javax.swing.JRadioButton radBtnPendiente;
    private javax.swing.JRadioButton radBtnProceso;
    private javax.swing.JRadioButton radBtnTerminadas;
    private javax.swing.JTable tablaTareas;
    // End of variables declaration//GEN-END:variables
}
