/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controlador.ComentariosData;
import Controlador.EquipoData;
import Controlador.EquipoMiembrosData;
import Controlador.MiembroData;
import Controlador.ProyectoData;
import Controlador.TareaData;
import Modelo.Comentarios;
import Modelo.Miembro;
import Modelo.Proyecto;
import Modelo.Tarea;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewHistorialComentarios extends javax.swing.JFrame {

    private ProyectoData proyecData;
    private EquipoData equiData;
    private EquipoMiembrosData equiMiemData;
    private MiembroData miemData;
    private TareaData tareaData;
    private ComentariosData comData;
    private Miembro miemSel;
    private Tarea tareaSel;
    private DefaultTableModel modelo;
    private int idEquipo;

    /**
     * Creates new form ViewIncorporarMiembroEquipo2
     */
    public ViewHistorialComentarios() {
        initComponents();
        modelo = new DefaultTableModel();
        armarCabeceraTabla();
        limpiarTabla();
        llenarTabla();
    }

    ViewHistorialComentarios(ProyectoData proyecData, EquipoData equiData, EquipoMiembrosData equiMiemData, MiembroData miemData, TareaData tareaData, ComentariosData comData, Miembro miemSel, Tarea tareaSel, int idEquipo) {
        initComponents();
        this.proyecData = proyecData;
        this.equiData = equiData;
        this.equiMiemData = equiMiemData;
        this.miemData = miemData;
        this.tareaData = tareaData;
        this.comData = comData;
        this.miemSel = miemSel;
        this.tareaSel = tareaSel;
        this.idEquipo = idEquipo;

        modelo = new DefaultTableModel();
        armarCabeceraTabla();
        limpiarTabla();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel23 = new javax.swing.JPanel();
        lblTituloC = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblNroEquipo = new javax.swing.JLabel();
        lblComentario = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMiemEquipo = new javax.swing.JTable();
        lblComentario1 = new javax.swing.JLabel();
        lblComentario2 = new javax.swing.JLabel();
        btnEliminarComentario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloC.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        lblTituloC.setText("Historial Comentarios de Tarea");

        btnSalir.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblNroEquipo.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        lblNroEquipo.setText(" ");

        lblComentario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblComentario.setText("                                                                                                           ");

        tablaMiemEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaMiemEquipo);

        lblComentario1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblComentario1.setText("Tarea:");

        lblComentario2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblComentario2.setText("Comentarios:");

        btnEliminarComentario.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnEliminarComentario.setText("Eliminar comentario");
        btnEliminarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarComentarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloC, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(btnEliminarComentario)
                        .addGap(39, 39, 39)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel23Layout.createSequentialGroup()
                            .addComponent(lblComentario1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(lblNroEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(lblComentario2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloC)
                    .addComponent(lblNroEquipo))
                .addGap(27, 27, 27)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComentario1)
                    .addComponent(lblComentario))
                .addGap(16, 16, 16)
                .addComponent(lblComentario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        ViewVerTarea ppalBusEquipo = new ViewVerTarea(proyecData, equiData, equiMiemData, miemData, tareaData, comData, idEquipo);
        ppalBusEquipo.setVisible(true);
        ppalBusEquipo.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarComentarioActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tablaMiemEquipo.getSelectedRow();

        if (selectedRowIndex != -1) {

            selectedRowIndex = tablaMiemEquipo.convertRowIndexToModel(selectedRowIndex);

            int idComentario = (int) modelo.getValueAt(selectedRowIndex, 1);
            comData.eliminaComentario(idComentario);
            modelo.removeRow(selectedRowIndex);
        } else {
            JOptionPane.showMessageDialog(null, "No seleccionó ningún comentario para eliminar.");
        }


    }//GEN-LAST:event_btnEliminarComentarioActionPerformed
    private void llenarTabla() {
        limpiarTabla();
        List<Comentarios> listaComentarios = new ArrayList<Comentarios>();

        listaComentarios = comData.listarComentariosPorIdTarea(tareaSel.getIdTarea());
        int cont = 0;
        for (Comentarios com : listaComentarios) {
            cont++;
            modelo.addRow(new Object[]{cont, com.getIdComentario(), com.getFechaAvance(), com.getComentario()});
        }

    }

    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("N°");
        filaCabecera.add("Orden");
        filaCabecera.add("Fecha");
        filaCabecera.add("Comentario");

        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        tablaMiemEquipo.setModel(modelo);

        tablaMiemEquipo.getColumnModel().getColumn(0).setPreferredWidth(5);
        tablaMiemEquipo.getColumnModel().getColumn(1).setPreferredWidth(10);
        tablaMiemEquipo.getColumnModel().getColumn(2).setPreferredWidth(45);
        tablaMiemEquipo.getColumnModel().getColumn(3).setPreferredWidth(300);

        lblComentario.setText(tareaSel.getNombre());
    }

    private void limpiarTabla() {
        int filasModelo = modelo.getRowCount();
        for (int i = 0; i < filasModelo; i++) {
            modelo.removeRow(0);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarComentario;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblComentario;
    private javax.swing.JLabel lblComentario1;
    private javax.swing.JLabel lblComentario2;
    private javax.swing.JLabel lblNroEquipo;
    private javax.swing.JLabel lblTituloC;
    private javax.swing.JTable tablaMiemEquipo;
    // End of variables declaration//GEN-END:variables
}
