/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controlador.MiembroData;

/**
 *
 * @author user
 */
public class ViewPpalMiembro extends javax.swing.JFrame {

    private MiembroData miemData;

    /**
     * Creates new form ViewPpalMiembro
     */
    public ViewPpalMiembro() {
        initComponents();
    }

    ViewPpalMiembro(MiembroData miemData) {
        initComponents();
        this.miemData = miemData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnBuscarMiembro = new javax.swing.JButton();
        btnListadoPersonal = new javax.swing.JButton();
        lblTituloMiembro = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnIncorporarMiembro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscarMiembro.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnBuscarMiembro.setText("Buscar Miembro");
        btnBuscarMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMiembroActionPerformed(evt);
            }
        });

        btnListadoPersonal.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnListadoPersonal.setText("Listado del Personal");
        btnListadoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoPersonalActionPerformed(evt);
            }
        });

        lblTituloMiembro.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        lblTituloMiembro.setText("Miembro GestionAr");

        btnSalir.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnSalir.setText("Atras");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnIncorporarMiembro.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnIncorporarMiembro.setText("Incorporar Miembro");
        btnIncorporarMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncorporarMiembroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnListadoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTituloMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBuscarMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(btnIncorporarMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(372, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblTituloMiembro)
                .addGap(49, 49, 49)
                .addComponent(btnBuscarMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnListadoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(btnIncorporarMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(277, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMiembroActionPerformed
        // TODO add your handling code here:

        ViewBuscarMiembro buscarMiembro = new ViewBuscarMiembro(miemData);
        buscarMiembro.setVisible(true);
        buscarMiembro.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBuscarMiembroActionPerformed

    private void btnListadoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoPersonalActionPerformed
        // TODO add your handling code here:

        ViewListadoPersonal listadoPersonal = new ViewListadoPersonal(miemData);
        listadoPersonal.setVisible(true);
        listadoPersonal.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_btnListadoPersonalActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        ViewPpal ppal = new ViewPpal();
        ppal.setVisible(true);
        ppal.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIncorporarMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncorporarMiembroActionPerformed
        // TODO add your handling code here:
        ViewCrearMiembro crearMiembro = new ViewCrearMiembro(miemData);
        crearMiembro.setVisible(true);
        crearMiembro.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_btnIncorporarMiembroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMiembro;
    private javax.swing.JButton btnIncorporarMiembro;
    private javax.swing.JButton btnListadoPersonal;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTituloMiembro;
    // End of variables declaration//GEN-END:variables
}
