/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Controlador.MiembroData;
import Modelo.Miembro;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ViewListadoPersonal extends javax.swing.JFrame {

    private MiembroData miemData;
    private DefaultTableModel modelo;
    private DefaultTableModel modelo2;

    /**
     * Creates new form ViewListadoPersonal
     */
    public ViewListadoPersonal() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo2 = new DefaultTableModel();
        armarCabeceraTabla();
        limpiarTabla();
        llenarTabla();
    }

    ViewListadoPersonal(MiembroData miemData) {
        initComponents();
        this.miemData = miemData;
        modelo = new DefaultTableModel();
        modelo2 = new DefaultTableModel();
        armarCabeceraTabla();
        limpiarTabla();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnModificarPersonal = new javax.swing.JButton();
        lblSubTituloListado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListadoPersonal = new javax.swing.JTable();
        lblTituloListadoPersonal = new javax.swing.JLabel();
        lblSubTituloListado2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaListadoInactivos = new javax.swing.JTable();
        btnReincorporar = new javax.swing.JButton();
        btnSalir2 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnModificarPersonal.setBackground(new java.awt.Color(240, 63, 65));
        btnModificarPersonal.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnModificarPersonal.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarPersonal.setText("Modificar");
        btnModificarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPersonalActionPerformed(evt);
            }
        });

        lblSubTituloListado.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblSubTituloListado.setText("Totalidad de Miembros Activos");

        tablaListadoPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaListadoPersonal);

        lblTituloListadoPersonal.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        lblTituloListadoPersonal.setText("Listado Personal GestionArG1");

        lblSubTituloListado2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblSubTituloListado2.setText("Miembros Inactivos");

        tablaListadoInactivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaListadoInactivos);

        btnReincorporar.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnReincorporar.setText("Reincorporar");
        btnReincorporar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReincorporarActionPerformed(evt);
            }
        });

        btnSalir2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        btnSalir2.setText("Salir");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReincorporar)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModificarPersonal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblTituloListadoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(lblSubTituloListado))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(lblSubTituloListado2)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(589, Short.MAX_VALUE)
                    .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTituloListadoPersonal)
                .addGap(59, 59, 59)
                .addComponent(lblSubTituloListado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblSubTituloListado2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnModificarPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReincorporar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(561, Short.MAX_VALUE)
                    .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(15, 15, 15)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPersonalActionPerformed
        // TODO add your handling code here:

        int opcion = JOptionPane.showConfirmDialog(this, "¿Desea realizar alguna modificacion?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            //si confirma que si, empezar con el codigo aca abajo
            ViewBuscarMiembro buscarMiembro = new ViewBuscarMiembro(miemData);
            buscarMiembro.setVisible(true);
            buscarMiembro.setLocationRelativeTo(null);
            this.dispose();

    }//GEN-LAST:event_btnModificarPersonalActionPerformed
    }
    private void btnReincorporarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReincorporarActionPerformed

        // TODO add your handling code here:
        // Obteniendo la fila seleccionada
        int filaSeleccionada = tablaListadoInactivos.getSelectedRow();

        if (filaSeleccionada != -1) {
            // Obteniendo los datos de la fila seleccionada
            int idMiembro = (int) modelo2.getValueAt(filaSeleccionada, 0);

            // Activando el miembro
            miemData.activarMiembro(idMiembro);

            // Actualizando la tabla
            llenarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila primero");
        }
    }//GEN-LAST:event_btnReincorporarActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        // TODO add your handling code here:
        ViewPpalMiembro ppalMiembro = new ViewPpalMiembro(miemData);
        ppalMiembro.setVisible(true);
        ppalMiembro.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaListadoPersonal.getSelectedRow();

        if (filaSeleccionada != -1) {
            // Obteniendo los datos de la fila seleccionada
            int idMiembro = (int) modelo.getValueAt(filaSeleccionada, 0);

            // Activando el miembro
            miemData.eliminarMiembro(idMiembro);

            // Actualizando la tabla
            llenarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila primero");
        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Legajo");
        filaCabecera.add("Apellido");
        filaCabecera.add("Nombre");
        filaCabecera.add("DNI");

        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        tablaListadoPersonal.setModel(modelo);

        for (Object it : filaCabecera) {
            modelo2.addColumn(it);
        }
        tablaListadoInactivos.setModel(modelo2);

    }

    private void llenarTabla() {

        limpiarTabla();
        List<Miembro> listaActivos = new ArrayList<Miembro>();
        List<Miembro> listaInactivos = new ArrayList<Miembro>();

        listaActivos = miemData.listarMiembro();
        listaInactivos = miemData.listarMiembrosInactivos();

        for (Miembro miembro : listaActivos) {
            modelo.addRow(new Object[]{miembro.getIdMiembro(), miembro.getApellido(), miembro.getNombre(), miembro.getDni()});
        }

        for (Miembro miembro : listaInactivos) {
            modelo2.addRow(new Object[]{miembro.getIdMiembro(), miembro.getApellido(), miembro.getNombre(), miembro.getDni()});
        }

    }

    private void limpiarTabla() {
        int filasModelo = modelo.getRowCount();
        for (int i = 0; i < filasModelo; i++) {
            modelo.removeRow(0);
        }

        int filasModelo2 = modelo2.getRowCount();
        for (int i = 0; i < filasModelo2; i++) {
            modelo2.removeRow(0);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificarPersonal;
    private javax.swing.JButton btnReincorporar;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSubTituloListado;
    private javax.swing.JLabel lblSubTituloListado2;
    private javax.swing.JLabel lblTituloListadoPersonal;
    private javax.swing.JTable tablaListadoInactivos;
    private javax.swing.JTable tablaListadoPersonal;
    // End of variables declaration//GEN-END:variables
}
